openapi: 3.0.2
info:
  license:
    name: Placeholder
    url: 'https://loremipsum.com'
  version: '1.0'
  title: Welcome to the Grade Scale API!
  description: This API allows users to view the grade scale
  contact:
    url: 'http://localhost:5001/api'
    email: rohan.chandra@developersinstitute.co.nz
    name: Rohan Chandra
servers:
  - url: 'http://localhost:5001/api'
    description: Development server
paths:
  /grade-scale:
    get:
      summary: Returns the grade scale
      description: Get the grade scale
      operationId: get-grade-scale
      tags:
        - grade-scale
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Grade'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Grade:
      type: array
      items:
        type: object
        properties:
          id:
            type: number
          level:
            type: string
          minMark:
            type: integer
          maxMark:
            type: integer
          grade:
            type: string
        required:
          - level
          - minMark
          - maxMark
          - grade
    Error:
      type: object
      properties:
        message:
          type: string
tags:
  - name: grade-scale
    description: grade-calculator
